const SET_MOVIES = "SET_MOVIES";

const LIKE = "LIKE";

const BLOCK = "BLOCK";

const LOAD_DATA = "LOAD_DATA";

const DELETE_LIKE = "DELETE_LIKE";

const BLOCK_LIKE = "BLOCK_LIKE";

export default {SET_MOVIES, LIKE, BLOCK, LOAD_DATA, DELETE_LIKE, BLOCK_LIKE};