const SET_MOVIES = "SET_MOVIES";


const SORT_MOVIES = "SORT_MOVIES";


const LIKE = "LIKE";

const BLOCK = "BLOCK";

const LOAD_DATA = "LOAD_DATA";

const DELETE_LIKE = "DELETE_LIKE";

const BLOCK_LIKE = "BLOCK_LIKE";


const DELETE_BLOCK="DELETE_BLOCK";

const LIKE_BLOCK="LIKE_BLOCK";

export default {SET_MOVIES, SORT_MOVIES, LIKE, BLOCK, LOAD_DATA, DELETE_LIKE, BLOCK_LIKE, DELETE_BLOCK,LIKE_BLOCK};

